### ISSUE TITLE
Ordering of Clustering Arguments

### ISSUE THREAD

**Issue by wraseman** [joshhjacobson/parasol#4]
I've noticed a number of issues with the clustering arguments. First of all, the arguments only seem to work correctly when typed in the correct order (i.e., cluster(k, chartIDs, vars, palette, options, std, hidden))

For instance, the following works as expected: 

  var ps = Parasol(data)('.parcoords')
            .cluster(k=3,
                chartIDs = [0,1,2],
                vars = cluster_vars,
                palette = d3.schemeAccent,
                options = {},
                std = true,
                hidden = true)

But this does not:

  var ps = Parasol(data)('.parcoords')
            .cluster(k=3,
                chartIDs = [0,1,2],
                vars = cluster_vars,
                options = {},
                std = true,
                palette = d3.schemeAccent,
                hidden = true)

**Comment by wraseman** [comment]
Also, it would be more intuitive if Parasol.<b>cluster</b>() could be used without the user having to input any arguments at all. To do this, we would need to have a default k (I would suggest 3) and chartIDs (I would suggest all Parasol charts).

**Comment by joshhjacobson** [comment]
This is a result of the gaps in my knowledge of basic Javascript. Turns out named parameters aren't allowed! The fix is pretty simple though, and will actually be more flexible in the long run. [This thread](https://stackoverflow.com/questions/32868191/pass-a-value-to-a-specific-parameter-without-caring-about-the-position-of-the-pa) and  [this thread](https://stackoverflow.com/questions/11796093/named-parameters-in-javascript) provide a good idea of what is going on.

I'll close the issue after I implement an official solution.
